default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kieska 

development:
  <<: *default
  database: KieranDB
  adapter: mysql2
  host: kierandbmysql-do-user-10599195-0.b.db.ondigitalocean.com
  port: 25060
  socket: /var/run/mysqld/mysqld.sock
  password: mPCOCzRIJaPjSuux 
  sslmode: REQUIRED
  
secondbase:
  development:
    <<: *default
    database: KieranDB
    adapter: postgresql
    host: kierandb-do-user-10599195-0.b.db.ondigitalocean.com
    port: 25060
    password: wBumpC202CHv87rB 
    sslmode: require
    